//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BorrowBooks = new HashSet<BorrowBook>();
            this.BorrowedBooks = new HashSet<BorrowedBook>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Information { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Stock { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public virtual studentt studentt { get; set; }
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowBook> BorrowBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowedBook> BorrowedBooks { get; set; }
        public string AuthorName { get; set; }
    }
}
